name: Run Emacs Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y emacs
        emacs --version

    - name: Run tests
      run: emacs -batch -l test/run-tests.el
